site_name: OCA for Krita
site_url: https://oca-krita.rxlab.guide
repo_url: https://github.com/RxLaboratory/OCA-Krita/
edit_uri: edit/master/src-docs/docs
site_description: The OCA for Krita comprehensive documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2020-2022 RxLaboratory, Nicolas Dufresne and contributors'
use_directory_urls: false
theme:
    name: null
    custom_dir: 'cinder'
    colorscheme: zenburn
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - fenced_code
    - attr_list
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
    - meta.js
    - collapser.js
site_dir: ../docs/
dev_addr: '127.0.0.1:8001'
nav:
    - v1.4.0: index.md
    - User Guide:
        - Installation: install.md
        - Layer Tags: layer-tags.md
        - Blending Modes: blending-modes.md
        - Settings: settings.md
    - Misc:
        - Changelog: https://codeberg.org/RxLaboratory/OCA-Krita/releases
        - License:
            - GNU GPLv3: licenses/gnu-gpl.md
            - Documentation license: licenses/gfdl.md
        - Contact: http://contact.rxlab.info/
        - Donate: http://donate.rxlab.info/
